-- Agentic lending lab: teardown
--
-- Removes everything the lab created. Run as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

DROP DATABASE IF EXISTS LENDING;
DROP DATABASE IF EXISTS LAB_SETUP;
DROP WAREHOUSE IF EXISTS LENDING_WH;
DROP ROLE IF EXISTS LENDING_ROLE;
DROP API INTEGRATION IF EXISTS LAB_GIT_API;
